---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/alpine-s6:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/alpine-s6:latest
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:latest nephatrine/alpine-s6:latest
  - HOME=/mnt/config/home docker push nephatrine/alpine-s6:latest
  - docker rmi pdr.nephatrine.net/nephatrine/alpine-s6:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-drone-ci@master
      - nephatrine/docker-gitea-web@master
      - nephatrine/docker-minecraft-mcu@master
      - nephatrine/docker-nginx-ssl@master
      - nephatrine/docker-registry@master

depends_on:
- default

---
kind: signature
hmac: fa0f8c99e5d5c8260cf64eb0e1e0e75b428a6720015db73c1f203efb35fc515f

...
