---
kind: pipeline
type: exec
name: buildamd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:latest-amd64 .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/alpine-s6:latest-amd64
  - docker logout pdr.nephatrine.net
  - sleep 10

---
kind: pipeline
type: exec
name: buildarm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:latest-arm64v8 .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/alpine-s6:latest-arm64v8
  - docker logout pdr.nephatrine.net
  - sleep 10

---
kind: pipeline
type: exec
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - sleep 10
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker pull pdr.nephatrine.net/nephatrine/alpine-s6:latest-amd64
  - docker pull pdr.nephatrine.net/nephatrine/alpine-s6:latest-arm64v8
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:latest-amd64 nephatrine/alpine-s6:latest-amd64
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:latest-arm64v8 nephatrine/alpine-s6:latest-arm64v8
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push nephatrine/alpine-s6:latest-amd64
  - docker push nephatrine/alpine-s6:latest-arm64v8
  - docker manifest create nephatrine/alpine-s6:latest --amend nephatrine/alpine-s6:latest-amd64 --amend nephatrine/alpine-s6:latest-arm64v8
  - docker manifest create nephatrine/alpine-s6:3.1.4.2 --amend nephatrine/alpine-s6:latest-amd64 --amend nephatrine/alpine-s6:latest-arm64v8
  - docker manifest create nephatrine/alpine-s6:3.1.4 --amend nephatrine/alpine-s6:latest-amd64 --amend nephatrine/alpine-s6:latest-arm64v8
  - docker manifest create nephatrine/alpine-s6:3.1 --amend nephatrine/alpine-s6:latest-amd64 --amend nephatrine/alpine-s6:latest-arm64v8
  - docker manifest create nephatrine/alpine-s6:3 --amend nephatrine/alpine-s6:latest-amd64 --amend nephatrine/alpine-s6:latest-arm64v8
  - docker manifest push --purge nephatrine/alpine-s6:latest
  - docker manifest push --purge nephatrine/alpine-s6:3.1.4.2
  - docker manifest push --purge nephatrine/alpine-s6:3.1.4
  - docker manifest push --purge nephatrine/alpine-s6:3.1
  - docker manifest push --purge nephatrine/alpine-s6:3
  - docker logout
  depends_on:
  - pull

depends_on:
- buildamd64
- buildarm64

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- manifest

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: propogate-downstream
  image: plugins/downstream
  failure: ignore
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
    - nephatrine/docker-drone-ci@master
    - nephatrine/docker-gitea-web@master
    - nephatrine/docker-minecraft-mcu@master
    - nephatrine/docker-nginx-ssl@master
    - nephatrine/docker-registry@master

depends_on:
- manifest

---
kind: signature
hmac: 910c446647fc7af097688b3ff7df808119b21f1bbd3a5ef59e2c9b81c5e6a77a

...
