---
kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: construct
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/alpine-builder:latest . -f Dockerfile.builder
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/alpine-s6:latest .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/alpine-builder:latest
  - docker push pdr.nephatrine.net/nephatrine/alpine-s6:latest
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:latest nephatrine/alpine-s6:latest
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push nephatrine/alpine-s6:latest
  - docker logout

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- build

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: propogate-downstream
  image: plugins/downstream
  failure: ignore
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-drone-ci@master
      - nephatrine/docker-gitea-web@master
      - nephatrine/docker-minecraft-mcu@master
      - nephatrine/docker-nginx-ssl@master
      - nephatrine/docker-registry@master

depends_on:
- build

---
kind: signature
hmac: 74009d82741f8c4ec6d16ac4154d7378fb42ce23def0f5828293f22f4c3f1206

...
