---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/alpine-s6:testing .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/alpine-s6:testing
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:testing nephatrine/alpine-s6:testing
  - HOME=/mnt/config/home docker push nephatrine/alpine-s6:testing
  - docker rmi pdr.nephatrine.net/nephatrine/alpine-s6:testing

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-drone-ci@testing
      - nephatrine/docker-gitea-web@testing
      - nephatrine/docker-nginx-ssl@testing
      - nephatrine/docker-registry@testing

depends_on:
- default

---
kind: signature
hmac: d4cf9a3bcc800796db1c8ee0ef0466a9dfda61bef1cc3ab4587256a930d2887c

...
