---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-3.13
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/alpine-s6:3.13 . -f Dockerfile.313
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/alpine-s6:3.13
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:3.13 nephatrine/alpine-s6:3.13
  - HOME=/mnt/config/home docker push nephatrine/alpine-s6:3.13
  - docker rmi pdr.nephatrine.net/nephatrine/alpine-s6:3.13
- name: build-latest
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/alpine-s6:latest . -f Dockerfile
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/alpine-s6:latest
  - docker tag pdr.nephatrine.net/nephatrine/alpine-s6:latest nephatrine/alpine-s6:latest
  - HOME=/mnt/config/home docker push nephatrine/alpine-s6:latest
  - docker rmi pdr.nephatrine.net/nephatrine/alpine-s6:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-drone-ci@master
      - nephatrine/docker-gitea-web@master
      - nephatrine/docker-minecraft-mcu@master
      - nephatrine/docker-nginx-ssl@master
      - nephatrine/docker-registry@master

depends_on:
- default

---
kind: signature
hmac: a2ebeda44eee009b487f884142769020304ce0e664de6ed9a9b2e599d9a62f7c

...
