version = 1
SPDX-PackageName = "docker-alpine-s6"
SPDX-PackageSupplier = "Daniel Wolf <nephatrine@gmail.com>"
SPDX-PackageDownloadLocation = "https://code.nephatrine.net/NephNET/docker-alpine-s6"

[[annotations]]
path = [".vscode/*"]
SPDX-FileCopyrightText = "Daniel Wolf <nephatrine@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/crond/dependencies.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/logrotate_setup/dependencies.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/crond/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/guardian_setup/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/logrotate_setup/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/timezone_setup/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/user/contents.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
