#!/command/with-contenv /bin/bash

if [ -f /mnt/config/etc/crontabs/root ]; then
  if ! /usr/bin/diff /etc/crontabs/root /mnt/config/etc/crontabs/root >/dev/null 2>&1; then
    /usr/bin/crontab -u root /mnt/config/etc/crontabs/root
  fi
elif [ -f /etc/crontabs.default.d/root ]; then
  if ! /usr/bin/diff /etc/crontabs/root /etc/crontabs.default.d/root >/dev/null 2>&1; then
    /usr/bin/crontab -u root /etc/crontabs.default.d/root
  fi
elif [ -f /etc/crontabs/root ]; then
  /usr/bin/crontab -u root -r
fi

if [ -f /mnt/config/etc/crontabs/guardian ]; then
  if ! /usr/bin/diff /etc/crontabs/guardian /mnt/config/etc/crontabs/guardian >/dev/null 2>&1; then
    /usr/bin/crontab -u guardian /mnt/config/etc/crontabs/guardian
  fi
elif [ -f /etc/crontabs.default.d/guardian ]; then
  if ! /usr/bin/diff /etc/crontabs/guardian /etc/crontabs.default.d/guardian >/dev/null 2>&1; then
    /usr/bin/crontab -u guardian /etc/crontabs.default.d/guardian
  fi
elif [ -f /var/spool/cron/crontabs/guardian ]; then
  /usr/bin/crontab -u guardian -r
fi

exit 0
