#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-100}

usermod -o -u "$PUID" guardian
groupmod -o -g "$PGID" users

if [[ ! -d /mnt/config/home ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/home
fi
if [[ -d /etc/skel ]]; then
  s6-setuidgid guardian cp -Ran /etc/skel/. /mnt/config/home/
fi