#!/usr/bin/with-contenv bash

if [[ ! -d /mnt/config/log ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/log
fi

if [[ ! -f /mnt/config/etc/logrotate.conf ]]; then
  if [[ ! -d /mnt/config/etc ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/etc
  fi
  s6-setuidgid guardian cp /etc/logrotate.conf /mnt/config/etc/logrotate.conf
fi

if [[ ! -d /mnt/config/etc/logrotate.d ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/logrotate.d
fi
s6-setuidgid guardian cp -n /etc/logrotate.d/* /mnt/config/etc/logrotate.d/