#!/bin/bash

# Make Log Directory

if [[ ! -d /mnt/config/log ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/log
fi

if [[ -f /mnt/config/log/crond.log ]]; then
  chown guardian:users /mnt/config/log/crond.log
else
  /command/s6-setuidgid guardian /bin/touch /mnt/config/log/crond.log
fi

# Store Backup Crontabs

if [[ ! -d /etc/crontabs.default.d ]]; then
  /bin/mkdir -p /etc/crontabs.default.d
  if [[ -d /var/spool/cron/crontabs ]]; then
    /bin/cp -a /var/spool/cron/crontabs/* /etc/crontabs.default.d/
  fi
fi

# Build Root Crontab

THISTAB="/mnt/config/etc/crontabs/root"
if [[ ! -f "${THISTAB}" ]]; then
  if [[ -f /etc/crontabs.default.d/root || -f /etc/crontabs.custom.d/root ]]; then
    if [[ ! -d /mnt/config/etc/crontabs ]]; then
      /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc/crontabs
    fi
    
    echo '# NOTE: THIS IS THE ROOT CRONTAB - USE "s6-setuidgid guardian" TO ENSURE PROPER' | /command/s6-setuidgid guardian /usr/bin/tee "${THISTAB}" >/dev/null
    echo '#       PERMISSIONS WHEN INTERACTING WITH MOUNTED VOLUME.' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    
    if [[ -f /etc/crontabs.default.d/root ]]; then
      echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
      /bin/cat /etc/crontabs.default.d/root | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    fi
    if [[ -f /etc/crontabs.custom.d/root ]]; then
      echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
      /bin/cat /etc/crontabs.custom.d/root | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    fi
    echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    /bin/chmod 600 "${THISTAB}"
  fi
fi

# Build Guardian Crontab

THISTAB="/mnt/config/etc/crontabs/guardian"
if [[ ! -f "${THISTAB}" ]]; then
  if [[ -f /etc/crontabs.default.d/guardian || -f /etc/crontabs.custom.d/guardian ]]; then
    if [[ ! -d /mnt/config/etc/crontabs ]]; then
      /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc/crontabs
    fi
    
    echo '# NOTE: THIS IS THE VOLUME OWNER CRONTAB.' | /command/s6-setuidgid guardian /usr/bin/tee "${THISTAB}" >/dev/null
    
    if [[ -f /etc/crontabs.default.d/guardian ]]; then
      echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
      /bin/cat /etc/crontabs.default.d/guardian | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    fi
    if [[ -f /etc/crontabs.custom.d/guardian ]]; then
      echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
      /bin/cat /etc/crontabs.custom.d/guardian | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    fi
    echo '' | /command/s6-setuidgid guardian /usr/bin/tee -a "${THISTAB}" >/dev/null
    /bin/chmod 600 "${THISTAB}"
  fi
fi

/etc/periodic/15min/watcher-crond
exec /usr/sbin/crond -L /mnt/config/log/crond.log -l 6 -f;
