#!/command/with-contenv /bin/bash

EXITVALUE=0

if [[ -f /mnt/config/etc/logrotate.conf ]]; then
  if [[ ! -d /mnt/config/log ]]; then
    /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/log
  fi
  
  cd /mnt/config/log
  /usr/bin/test -e logrotate.status || /command/s6-setuidgid guardian /bin/touch logrotate.status
  /usr/bin/head -1 logrotate.status | /command/s6-setuidgid guardian /usr/bin/tee logrotate.clean
  /bin/sed 's/"//g' logrotate.status | while read logfile date; do
    [ -e "$logfile" ] && echo "\"$logfile\" $date"
  done | /command/s6-setuidgid guardian /usr/bin/tee -a logrotate.clean
  /command/s6-setuidgid guardian /bin/mv logrotate.clean logrotate.status

  if [ -f /etc/conf.d/logrotate ]; then
    . /etc/conf.d/logrotate
  fi
  if [ -x /usr/bin/cpulimit ] && [ -n "$CPULIMIT" ]; then
    _cpulimit="/usr/bin/cpulimit --limit=$CPULIMIT"
  fi

  $_cpulimit /command/s6-setuidgid guardian /usr/sbin/logrotate -s /mnt/config/log/logrotate.status -v /mnt/config/etc/logrotate.conf
  EXITVALUE=$?
fi

exit $EXITVALUE
